ascatACCamp <- read.table("ascatACCamplification.txt", sep = "\t")
ascatTPRamp <- read.table("ascatTPRamplification.txt", sep = "\t")
ascatTNRamp <- read.table("ascatTNRamplification.txt", sep = "\t")
ascatPPVamp <- read.table("ascatPPVamplification.txt", sep = "\t")
ascatFDRamp <- read.table("ascatFDRamplification.txt", sep = "\t")
colnames(ascatACCamp) <- c("ID", "ACC")
colnames(ascatTPRamp) <- c("ID", "TPR")
colnames(ascatTNRamp) <- c("ID", "TNR")
colnames(ascatPPVamp) <- c("ID", "PPV")
colnames(ascatFDRamp) <- c("ID", "FDR")
mer1 <- merge(ascatTPRamp, ascatTNRamp, by = "ID")
mer1 <- merge(mer1, ascatFDRamp, by = "ID")
mer1 <- merge(mer1, ascatPPVamp, by = "ID")
mer1 <- merge(mer1, ascatACCamp, by = "ID")
mer1 <- subset(mer1, select = c("TPR", "TNR", "FDR", "PPV", "ACC"))
boxplot(mer1, ylim = c(0, 1), main = "ascatNGS amplifications")

ascatACCdel <- read.table("ascatACCdeletion.txt", sep = "\t")
ascatTPRdel <- read.table("ascatTPRdeletion.txt", sep = "\t")
ascatTNRdel <- read.table("ascatTNRdeletion.txt", sep = "\t")
ascatPPVdel <- read.table("ascatPPVdeletion.txt", sep = "\t")
ascatFDRdel <- read.table("ascatFDRdeletion.txt", sep = "\t")
colnames(ascatACCdel) <- c("ID", "ACC")
colnames(ascatTPRdel) <- c("ID", "TPR")
colnames(ascatTNRdel) <- c("ID", "TNR")
colnames(ascatPPVdel) <- c("ID", "PPV")
colnames(ascatFDRdel) <- c("ID", "FDR")
mer2 <- merge(ascatTPRdel, ascatTNRamp, by = "ID")
mer2 <- merge(mer2, ascatFDRdel, by = "ID")
mer2 <- merge(mer2, ascatPPVdel, by = "ID")
mer2 <- merge(mer2, ascatACCdel, by = "ID")
mer2 <- subset(mer2, select = c("TPR", "TNR", "FDR", "PPV", "ACC"))
boxplot(mer2, ylim = c(0, 1), main = "ascatNGS Deletions")

facetsACCamp <- read.table("facetsACCamplification.txt", sep = "\t")
facetsTPRamp <- read.table("facetsTPRamplification.txt", sep = "\t")
facetsTNRamp <- read.table("facetsTNRamplification.txt", sep = "\t")
facetsPPVamp <- read.table("facetsPPVamplification.txt", sep = "\t")
facetsFDRamp <- read.table("facetsFDRamplification.txt", sep = "\t")
colnames(facetsACCamp) <- c("ID", "ACC")
colnames(facetsTPRamp) <- c("ID", "TPR")
colnames(facetsTNRamp) <- c("ID", "TNR")
colnames(facetsPPVamp) <- c("ID", "PPV")
colnames(facetsFDRamp) <- c("ID", "FDR")
mer3 <- merge(facetsTPRamp, ascatTNRamp, by = "ID")
mer3 <- merge(mer3, facetsFDRamp, by = "ID")
mer3 <- merge(mer3, facetsPPVamp, by = "ID")
mer3 <- merge(mer3, facetsACCamp, by = "ID")
mer3 <- subset(mer3, select = c("TPR", "TNR", "FDR", "PPV", "ACC"))
boxplot(mer3, ylim = c(0, 1), main = "FACETS amplifications")

facetsACCdel <- read.table("facetsACCdeletion.txt", sep = "\t")
facetsTPRdel <- read.table("facetsTPRdeletion.txt", sep = "\t")
facetsTNRdel <- read.table("facetsTNRdeletion.txt", sep = "\t")
facetsPPVdel <- read.table("facetsPPVdeletion.txt", sep = "\t")
facetsFDRdel <- read.table("facetsFDRdeletion.txt", sep = "\t")
colnames(facetsACCdel) <- c("ID", "ACC")
colnames(facetsTPRdel) <- c("ID", "TPR")
colnames(facetsTNRdel) <- c("ID", "TNR")
colnames(facetsPPVdel) <- c("ID", "PPV")
colnames(facetsFDRdel) <- c("ID", "FDR")
mer4 <- merge(facetsTPRdel, ascatTNRamp, by = "ID")
mer4 <- merge(mer4, facetsFDRdel, by = "ID")
mer4 <- merge(mer4, facetsPPVdel, by = "ID")
mer4 <- merge(mer4, facetsACCdel, by = "ID")
mer4 <- subset(mer4, select = c("TPR", "TNR", "FDR", "PPV", "ACC"))
boxplot(mer4, ylim = c(0, 1), main = "FACETS Deletions")

ascatJCamp <- read.table("ascatJaccardAmplification.txt", sep = "\t")
ascatJCdel <- read.table("ascatJaccardDeletion.txt", sep = "\t")
facetsJCamp <- read.table("facetsJaccardAmplification.txt", sep = "\t")
facetsJCdel <- read.table("facetsJaccardDeletion.txt", sep = "\t")
colnames(ascatJCamp) <- c("ID", "ascatNGS")
colnames(ascatJCdel) <- c("ID", "ascatNGS")
colnames(facetsJCamp) <- c("ID", "FACETS")
colnames(facetsJCdel) <- c("ID", "FACETS")
jcamp <- merge(facetsJCamp, ascatJCamp, by  = "ID")
jcamp <- subset(jcamp, select = c("ascatNGS", "FACETS"))
boxplot(jcamp, main = "Jaccard Index amplifications")
jcdel <- merge(facetsJCdel, ascatJCdel, by  = "ID")
jcdel <- subset(jcdel, select = c("ascatNGS", "FACETS"))
boxplot(jcdel, main = "Jaccard Index deletions", ylim = c(0, 0.4))

library(ggplot2)
ascatPurity <- read.table("ascatPurities.txt", sep = "\t")
facetsPurity <- read.table("facetsPurities.txt", sep = "\t")
colnames(ascatPurity) <- c("ID", "ascatNGS")
colnames(facetsPurity) <- c("ID", "FACETS")
purity <- merge(ascatPurity, facetsPurity, by = "ID")
ascatPloidy <- read.table("ascatPloidies.txt", sep = "\t")
facetsPloidy <- read.table("facetsPloidies.txt", sep = "\t")
colnames(ascatPloidy) <- c("ID", "ascatNGS")
colnames(facetsPloidy) <- c("ID", "FACETS")
ploidy <- merge(ascatPloidy, facetsPloidy, by = "ID")

plot(NULL, xlim = c(1, 2), ylim = c(0, 1), axes = F, main = "Purity", xlab = "", ylab = "")
segments(1, purity$ascatNGS, 2, purity$FACETS, col = alpha("blue", 0.3))
abline(v = 1, col = "black")
abline(v = 2, col = "black")
axis(1, at = c(1,2), labels = c("ascatNGS", "FACETS"), col = "white")
axis(2, at = c(0,1))

plot(NULL, xlim = c(1, 2), ylim = c(1, 9), axes = F, main = "Ploidy", xlab = "", ylab = "")
segments(1, ploidy$ascatNGS, 2, ploidy$FACETS, col = alpha("red", 0.3))
abline(v = 1, col = "black")
abline(v = 2, col = "black")
axis(1, at = c(1,2), labels = c("ascatNGS", "FACETS"), col = "white")
axis(2, at = c(1,2,3,4,5,6,7,8,9))