#################################################################
# Checking the combination purity and mean copy number reported #
#################################################################
library(ggplot2)
library(scales)

# Load the data
full <- read.table("meanCN.tsv", sep = "\t", header = TRUE)

# Purity correlation between LOH tools
purity <- data.frame(FACETS = full$fac_purity, Sequenza = full$seq_purity, PURPLE = full$pur_purity, ascatNGS = full$ngs_purity)
ggplot(purity, aes(FACETS, Sequenza)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Purity correlation") + theme_minimal()
ggsave("purityFvS.png")
ggplot(purity, aes(FACETS, PURPLE)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Purity correlation") + theme_minimal()
ggsave("purityFvP.png")
ggplot(purity, aes(FACETS, ascatNGS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Purity correlation") + theme_minimal()
ggsave("purityFvN.png")
ggplot(purity, aes(Sequenza, PURPLE)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Purity correlation") + theme_minimal()
ggsave("puritySvP.png")
ggplot(purity, aes(Sequenza, ascatNGS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Purity correlation") + theme_minimal()
ggsave("puritySvN.png")
ggplot(purity, aes(PURPLE, ascatNGS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Purity correlation") + theme_minimal()
ggsave("purityPvN.png")

# Mean CN correlation
cn <- data.frame(ASCAT2 = full$asc_meanCN, FACETS = full$fac_meanCN, Sequenza = full$seq_meanCN, PURPLE = full$pur_meanCN, ascatNGS = full$ngs_meanCN)
ggplot(cn, aes(ASCAT2, FACETS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Mean copy number") + theme_minimal()
ggsave("cnAvF.png")
ggplot(cn, aes(ASCAT2, Sequenza)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Mean copy number") + theme_minimal()
ggsave("cnAvS.png")
ggplot(cn, aes(ASCAT2, PURPLE)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Mean copy number") + theme_minimal()
ggsave("cnAvP.png")
ggplot(cn, aes(ASCAT2, ascatNGS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Mean copy number") + theme_minimal()
ggsave("cnAvN.png")
ggplot(cn, aes(FACETS, Sequenza)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Mean copy number") + theme_minimal()
ggsave("cnFvS.png")
ggplot(cn, aes(FACETS, PURPLE)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Mean copy number") + theme_minimal()
ggsave("cnFvP.png")
ggplot(cn, aes(FACETS, ascatNGS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Mean copy number") + theme_minimal()
ggsave("cnFvN.png")
ggplot(cn, aes(Sequenza, PURPLE)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Mean copy number") + theme_minimal()
ggsave("cnSvP.png")
ggplot(cn, aes(Sequenza, ascatNGS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Mean copy number") + theme_minimal()
ggsave("cnSvN.png")
ggplot(cn, aes(PURPLE, ascatNGS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Mean copy number") + theme_minimal()
ggsave("cnPvS.png")

# Mean CN correlation
ploidy <- data.frame(FACETS = full$fac_ploidy, Sequenza = full$seq_ploidy, PURPLE = full$pur_ploidy, ascatNGS = full$ngs_ploidy)
ggplot(ploidy, aes(FACETS, Sequenza)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Ploidy") + theme_minimal()
ggsave("plFvS.png")
ggplot(ploidy, aes(FACETS, PURPLE)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Ploidy") + theme_minimal()
ggsave("plFvP.png")
ggplot(ploidy, aes(FACETS, ascatNGS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Ploidy") + theme_minimal()
ggsave("plFvN.png")
ggplot(ploidy, aes(Sequenza, PURPLE)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Ploidy") + theme_minimal()
ggsave("plSvP.png")
ggplot(ploidy, aes(Sequenza, ascatNGS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Ploidy") + theme_minimal()
ggsave("plSvN.png")
ggplot(ploidy, aes(PURPLE, ascatNGS)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Ploidy") + theme_minimal()
ggsave("plPvS.png")

# Copy number reported
png("allCN.png", width = 720, height = 554)
boxplot(cn, col = hue_pal()(5), main = "Mean copy number reported")
dev.off()
png("allCN_outliers.png", width = 720, height = 554)
boxplot(cn, col = hue_pal()(5), main = "Mean copy number reported", outline = FALSE)
dev.off()

# Aberration percentage reported by each tool
colors <- hue_pal()(4)
tmp <- strsplit(full$asc_aberration, ";")
ascat <- matrix(as.numeric(unlist(tmp)), ncol = 4, byrow = TRUE)
png("ascat2Aberrations.png", width = 720, height = 554)
boxplot(ascat, names = c("Amp", "LOH", "Del", "WT"), col = colors, main = "ASCAT2")
dev.off()
tmp <- strsplit(full$fac_aberration, ";")
facets <- matrix(as.numeric(unlist(tmp)), ncol = 4, byrow = TRUE)
png("facetsAberrations.png", width = 720, height = 554)
boxplot(facets, names = c("Amp", "LOH", "Del", "WT"), col = colors, main = "FACETS")
dev.off()
tmp <- strsplit(full$seq_aberration, ";")
sequenza <- matrix(as.numeric(unlist(tmp)), ncol = 4, byrow = TRUE)
png("sequenzaAberrations.png", width = 720, height = 554)
boxplot(sequenza, names = c("Amp", "LOH", "Del", "WT"), col = colors, main = "Sequenza")
dev.off()
tmp <- strsplit(full$pur_aberration, ";")
purple <- matrix(as.numeric(unlist(tmp)), ncol = 4, byrow = TRUE)
png("purpleAberrations.png", width = 720, height = 554)
boxplot(purple, names = c("Amp", "LOH", "Del", "WT"), col = colors, main = "PURPLE")
dev.off()
tmp <- strsplit(full$ngs_aberration, ";")
ascatngs <- matrix(as.numeric(unlist(tmp)), ncol = 4, byrow = TRUE)
png("ascatngsAberrations.png", width = 720, height = 554)
boxplot(ascatngs, names = c("Amp", "LOH", "Del", "WT"), col = colors, main = "ascatNGS")
dev.off()
